version: '3'

services:
  api:
    build: .
    container_name: api
    restart: on-failure
    environment:
      DB_HOST: 'db'
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - veritran


networks:
  veritran:
    driver: bridge
