// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	entities "VERITRAN/internal/domain/account/entities"

	mock "github.com/stretchr/testify/mock"
)

// AccountCreate is an autogenerated mock type for the AccountCreate type
type AccountCreate struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *AccountCreate) Create(_a0 *entities.Account) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Account) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
